name: First Workflow

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: windows-latest

    steps:
      - name: Hello GitHub Action
        run: echo "Hello, this is my first workflow in GitHub Actions"

      - name: Bye GitHub Action
        run: echo "Bye, this is my first workflow in GitHub Actions"
