name: Second Workflow

on:
  push:

jobs:
  hello-job:
    runs-on: windows-latest

    steps:
      - name: "Welcome"
        run: echo "Welcome to the code step by step"

  boy-job:
    runs-on: windows-latest

    steps:
      - name: "Bye"
        run: echo "Bye to the code step by step"